Models/ErrorViewModel.cs
using System;

namespace BsacTimetableCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GroupViewModel.cs
using System;

namespace BsacTimetableCore.Models
{
    public class GroupViewModel
    {
        public int IdGroup { get; set; }
        public string NameGroup { get; set; }

    }
}

Models/LectureRecordViewModel.cs
using System;

namespace BsacTimetableCore.Models
{
    public class LectureRecordViewModel
    {
        public int IdRecord { get; set; }
        public int WeekDay { get; set; }
        public int WeekNumber { get; set; }
        public string GroupName { get; set; }
        public string SubjectName { get; set; }
        public int SubjOrdinalNumber { get; set; }
        public string Classroom { get; set; }
        public int IdSubjectType { get; set; }

    }
}

Models/LectureViewModel.cs
using System;

namespace BsacTimetableCore.Models
{
    public class LectureViewModel
    {
        public int IdLecturer { get; set; }
        public string NameLecturer { get; set; }

    }
}

Models/StudentRecordViewModel.cs
using System;

namespace BsacTimetableCore.Models
{
    public class StudentRecordViewModel
    {
        public int IdRecord { get; set; }
        public int WeekDay { get; set; }
        public int WeekNumber { get; set; }
        public string LectureName { get; set; }
        public string SubjectName { get; set; }
        public int SubjOrdinalNumber { get; set; }
        public string Classroom { get; set; }
    }
}

Controllers/LectureController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BsacTimetableCore.Models;
using BsacTimetableCore.DBContextAndModelsfolder;
using BsacTimetableCore.Services;

namespace BsacTimetableCore.Controllers
{
    public class LectureController : Controller
    {
        private readonly bsac_timetableContext _context;

        public LectureController(bsac_timetableContext context)
        {
            _context = context;
        }
        public IActionResult Index(string searchString, int? page)
        {
            ViewData["searchString"] = searchString;
            var lecturers = (from p in _context.Lecturer 
            select new LectureViewModel{IdLecturer = p.IdLecturer,  NameLecturer = p.NameLecturer});

            if (!String.IsNullOrEmpty(searchString))
            {
                lecturers = lecturers.Where(g => g.NameLecturer.Contains(searchString));
            }

            return View(PaginatedList<LectureViewModel>.Create(lecturers, page ?? 1, 10));
        }
        
        public IActionResult DetailsWeek(int id)
        {
            IAcessoryService service = new AcessoryService();
            ViewData["currWeek"] = service.GetCurrentWeek();
            ViewData["lectureName"] = (from p in _context.Lecturer
                                     where p.IdLecturer == id
                                     select p.NameLecturer).First();

            var records = (from r in _context.Record
                           join l in _context.Group on r.IdGroup equals l.IdGroup
                           join s in _context.Subject on r.IdSubject equals s.IdSubject
                           join c in _context.Classroom on r.IdClassroom equals c.IdClassroom
                           where (r.IdLecturer == id)

                           //    && (r.DateTo >= DateTime.Today && r.DateFrom <= DateTime.Today)
                           orderby r.WeekDay, r.SubjOrdinalNumber, r.WeekNumber
                           select new LectureRecordViewModel
                            {
                                IdRecord = r.IdRecord,
                                WeekDay = r.WeekDay,
                                WeekNumber = r.WeekNumber,
                                GroupName = l.NameGroup,
                                SubjectName = s.AbnameSubject,
                                SubjOrdinalNumber = r.SubjOrdinalNumber,
                                Classroom = c.Name + " (к." + c.Building + ")",
                                IdSubjectType = r.IdSubjectType
                            }
            ).ToList();

            return View(records);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BsacTimetableCore.Models;
using BsacTimetableCore.DBContextAndModelsfolder;
using BsacTimetableCore.Services;

namespace BsacTimetableCore.Controllers
{
    public class StudentController : Controller
    {
        private readonly bsac_timetableContext _context;

        public StudentController(bsac_timetableContext context)
        {
            _context = context;
        }
        public IActionResult Index(string searchString, int? page)
        {
            ViewData["searchString"] = searchString;
            var groups = (from p in _context.Group
                          orderby p.IdGroup
                          select new GroupViewModel { IdGroup = p.IdGroup, NameGroup = p.NameGroup });

            if (!String.IsNullOrEmpty(searchString))
            {
                groups = groups.Where(g => g.NameGroup.Contains(searchString));
            }

            return View(PaginatedList<GroupViewModel>.Create(groups, page ?? 1, 10));
        }

        public IActionResult DetailsWeek(int idgroup, int subgroup)
        {
            IAcessoryService service = new AcessoryService();
            ViewData["currWeek"] = service.GetCurrentWeek();
            ViewData["subgroup"] = subgroup;
            ViewData["groupName"] = (from p in _context.Group
                                     where p.IdGroup == idgroup
                                     select p.NameGroup).First();///sdfsdfsdffds

            var records = (from r in _context.Record
                           join l in _context.Lecturer on r.IdLecturer equals l.IdLecturer
                           join s in _context.Subject on r.IdSubject equals s.IdSubject
                           join c in _context.Classroom on r.IdClassroom equals c.IdClassroom
                           where (r.IdGroup == idgroup) &&
                           new[] { subgroup, 3 }.Contains(r.IdSubjectFor)

                           //    && (r.DateTo >= DateTime.Today && r.DateFrom <= DateTime.Today)
                           orderby r.WeekDay, r.SubjOrdinalNumber, r.WeekNumber
                           select new StudentRecordViewModel
                            {
                                IdRecord = r.IdRecord,
                                WeekDay = r.WeekDay,
                                WeekNumber = r.WeekNumber,
                                LectureName = l.NameLecturer,
                                SubjectName = s.AbnameSubject,
                                SubjOrdinalNumber = r.SubjOrdinalNumber,
                                Classroom = c.Name + " (к." + c.Building + ")",
                                IdSubjectType = r.IdSubjectType
                            }
            ).ToList();

            return View(records);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/Lecture/DetailsCurrWeek.cshtml
hi

Views/Lecture/DetailsWeek.cshtml
@model List<LectureRecordViewModel>;

<h4>@ViewData["currWeek"]-я учебная неделя</h4>
<h4>@ViewData["lectureName"]</h4>
@{
    var dayOfWeek = 0;
    var lessonsForFourWeeks = new List<LectureRecordViewModel>();
}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Время</th>
            <th colspan="2">1я неделя</th>
            <th colspan="2">2я неделя</th>
            <th colspan="2">3я неделя</th>
            <th colspan="2">4я неделя</th>
        </tr>
    </thead>
    <body>
        @for(var i = 0; i<Model.Count; i++)
        {
            
            @for(var j = 0; j<lessonsForFourWeeks.Count; j++)
            {
                if(lessonsForFourWeeks[j].SubjOrdinalNumber != Model[i].SubjOrdinalNumber || lessonsForFourWeeks[j].WeekDay != Model[i].WeekDay)
                {
                    @Html.Partial("_FourLessons", lessonsForFourWeeks)
                    lessonsForFourWeeks.Clear();
                }
            }
            lessonsForFourWeeks.Add(Model[i]);
            
            if (Model[i].WeekDay != dayOfWeek)
            {
                dayOfWeek = Model[i].WeekDay;
                @Html.Partial("_DayName", dayOfWeek)
            }

            if (i == Model.Count-1)
            {
                @Html.Partial("_FourLessons", lessonsForFourWeeks)
            }
            
            
        }
    </body>
</table>

Views/Lecture/Index.cshtml
@using BsacTimetableCore.DBContextAndModelsfolder;
@using BsacTimetableCore.Services;

@model PaginatedList<LectureViewModel>;


@{
    ViewData["Title"] = "Расписание для преподавателей";
}
<br>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Введите имя преподавателя (или часть, для поиска): <input type="text" name="searchString" value="@ViewData["searchString"]"/>
            <input type="submit" value="Поиск" class="btn btn-default" />
        </p>
    </div>
</form>

<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <h4>@(item.NameLecturer)</h4>
                </td>
                <td>
                    <a asp-action="DetailsWeek" asp-route-id="@(item.IdLecturer)" class="btn btn-info">Показать расписание</a>                
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-searchString="@ViewData["searchString"]"
   class="btn btn-default @prevDisabled">
    Предыдущая стр.
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-searchString="@ViewData["searchString"]"
   class="btn btn-default @nextDisabled">
    Следующая стр.
</a>

<h3>Найдено преподавателей: @Model.TotalCount </h3>

Views/Lecture/_FourLessons.cshtml
@model List<LectureRecordViewModel>

@functions {

    string getColorByType(int type)
    {
        var color = "";
        switch (type)
        {
            case 1: color = "#81ff57"; break;
            case 2: color = "#ffff4d"; break;
            case 3: color = "#ff704d"; break;
            case 4: color = "#cce6ff"; break;
            case 5: color = "#80c1ff"; break;
            case 6: color = "#e184c2"; break;
            case 7: color = "#99ffff"; break;
        }
        return color;
    }
    string getTypeNameByType(int type)
    {
        var name = "";
        switch (type)
        {
            case 1: name = "ЛК"; break;
            case 2: name = "ЛР"; break;
            case 3: name = "ПЗ"; break;
            case 4: name = "Конс."; break;
            case 5: name = "Зчт."; break;
            case 6: name = "Экз."; break;
            case 7: name = "Пер."; break;
        }
        return name;
    }
}

<tr>
    @{var j = 0;}
    @Html.Partial("_TimeTD", Model[0].SubjOrdinalNumber)
    @for(var i = 1; i<=4; i++)
    {
        

        if(Model.Count > j)
        {
            var color = getColorByType(Model[j].IdSubjectType);

            if(Model[j].WeekNumber == i)
            {
                while(true)
                {
                    if(Model.Count > j+1)
                    {
                        if(Model[j].WeekNumber == Model[j+1].WeekNumber)
                        { j++; }
                        else
                        { break; }
                    }
                    else
                    { break; }
                }
                <td style=@("background-color:"+color)>@(Model[j].SubjectName) (@getTypeNameByType(Model[j].IdSubjectType))     </td>
                <td style=@("background-color:"+color) rowspan="2" class="vertical-center">@Model[j].Classroom</td>
                j++;
            }
             else
            {
                <td></td>
                <td rowspan="2" class="vertical-center"></td>
            } 
        }
        else
        {
            <td></td>
            <td rowspan="2" class="vertical-center"></td>
        }
    }
    
</tr>
<tr>
    @{j = 0;}
    @for(var i = 1; i<=4; i++)
    {
        if(Model.Count > j)
        {
            var color = getColorByType(Model[j].IdSubjectType);

            if(Model[j].WeekNumber == i)
            {

                while(true)
                {
                    if(Model.Count > j+1)
                    {
                        if(Model[j].WeekNumber == Model[j+1].WeekNumber)
                        {
                            Model[j+1].GroupName += (" " + Model[j].GroupName);
                            j++;
                        }
                        else
                        { break; }
                    }
                    else
                    { break; }
                }

                <td style=@("background-color:"+color)>@(Model[j].GroupName)</td>
                j++;
            }
             else
            {
                <td></td>
            }
        }
        else
        {
            <td></td>
        }
    }

</tr>

Views/Shared/_DayName.cshtml
@model int

@switch (@Model)
    {
    case 1:
        <td colspan="9" align="center"><b>Понедельник</b></td>
        break;
    case 2:
        <td colspan="9" align="center"><b>Вторник</b></td>
        break;
     case 3:
        <td colspan="9" align="center"><b>Среда</b></td>
        break;
    case 4:
        <td colspan="9" align="center"><b>Четверг</b></td>
        break;
    case 5:
        <td colspan="9" align="center"><b>Пятница</b></td>
        break;
    case 6:
        <td colspan="9" align="center"><b>Суббота</b></td>
        break;
    case 7:
        <td colspan="9" align="center"><b>Воскресенье</b></td>
        break;
    }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BsacTimetableCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Student" asp-action="Index" class="navbar-brand">Расписание БГАС</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Student" asp-action="Index">Студентам</a></li>
                    <li><a asp-area="" asp-controller="Lecture" asp-action="Index">Преподавателям</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - BsacTimetableCore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TimeTD.cshtml
@model int

@switch (@Model)
    {
    case 1:
        <td rowspan="2" class="vertical-center">8.00-9.40</td>
        break;
    case 2:
        <td rowspan="2" class="vertical-center">9.55-11.35</td>
        break;
     case 3:
        <td rowspan="2" class="vertical-center">12.15-13.55</td>
        break;
    case 4:
        <td rowspan="2" class="vertical-center">14.10-15.50</td>
        break;
    case 5:
        <td rowspan="2" class="vertical-center">16.20-18.00</td>
        break;
    case 6:
        <td rowspan="2" class="vertical-center">18.15-19.55</td>
        break;
    case 7:
        <td rowspan="2" class="vertical-center">20.10-21.50</td>
        break;
    }

Views/Student/DetailsWeek.cshtml
@model List<StudentRecordViewModel>;


<h4>@ViewData["currWeek"]-я учебная неделя</h4>
<h4>@ViewData["groupName"], @ViewData["subgroup"]-я подгруппа</h4>
@{
    var dayOfWeek = 0;
    var lessonsForFourWeeks = new List<StudentRecordViewModel>();
}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Время</th>
            <th colspan="2">1я неделя</th>
            <th colspan="2">2я неделя</th>
            <th colspan="2">3я неделя</th>
            <th colspan="2">4я неделя</th>
        </tr>
    </thead>
    <body>
        @for(var i = 0; i<Model.Count; i++)
        {
            
            @for(var j = 0; j<lessonsForFourWeeks.Count; j++)
            {
                if(lessonsForFourWeeks[j].SubjOrdinalNumber != Model[i].SubjOrdinalNumber || lessonsForFourWeeks[j].WeekDay != Model[i].WeekDay)
                {
                    @Html.Partial("_FourLessons", lessonsForFourWeeks)
                    lessonsForFourWeeks.Clear();
                }
            }
            lessonsForFourWeeks.Add(Model[i]);
            
            if (Model[i].WeekDay != dayOfWeek)
            {
                dayOfWeek = Model[i].WeekDay;
                @Html.Partial("_DayName", dayOfWeek)
            }

            if (i == Model.Count-1)
            {
                @Html.Partial("_FourLessons", lessonsForFourWeeks)
            }
            
            
        }
    </body>
</table>

Views/Student/Index.cshtml
@using BsacTimetableCore.DBContextAndModelsfolder;
@using BsacTimetableCore.Services;

@model PaginatedList<GroupViewModel>;


@{
    ViewData["Title"] = "Расписание для студентов";
}
<br>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Введите название группы (или часть, для поиска): <input type="text" name="searchString" value="@ViewData["searchString"]"/>
            <input type="submit" value="Поиск" class="btn btn-default" />
        </p>
    </div>
</form>

<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <h4>@(item.NameGroup)</h4>
                </td>
                <td>
                    <a asp-action="DetailsWeek" asp-route-idgroup="@(item.IdGroup)" asp-route-subgroup=1 class="btn btn-info">Подгруппа 1</a>                
                    <a asp-action="DetailsWeek" asp-route-idgroup="@(item.IdGroup)" asp-route-subgroup=2 class="btn btn-warning">Подгруппа 2</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-searchString="@ViewData["searchString"]"
   class="btn btn-default @prevDisabled">
    Предыдущая стр.
</a>
<a asp-action="Index"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-searchString="@ViewData["searchString"]"
   class="btn btn-default @nextDisabled">
    Следующая стр.
</a>

<h3>Найдено групп: @Model.TotalCount </h3>

Views/Student/_FourLessons.cshtml
@model List<StudentRecordViewModel>

@functions 
{
    string getColorByType(int type)
    {
        var color = "";
        switch (type)
        {
            case 1: color = "#81ff57"; break;
            case 2: color = "#ffff4d"; break;
            case 3: color = "#ff704d"; break;
            case 4: color = "#cce6ff"; break;
            case 5: color = "#80c1ff"; break;
            case 6: color = "#e184c2"; break;
            case 7: color = "#99ffff"; break;
                                    


        }
        return color;
    }
    string getTypeNameByType(int type)
    {
        var name = "";
        switch (type)
        {
            case 1: name = "ЛК"; break;
            case 2: name = "ЛР"; break;
            case 3: name = "ПЗ"; break;
            case 4: name = "Конс."; break;
            case 5: name = "Зчт."; break;
            case 6: name = "Экз."; break;
            case 7: name = "Пер."; break;
        }
        return name;
    }
}

<tr>
    @{var j = 0;}
    @Html.Partial("_TimeTD", Model[0].SubjOrdinalNumber)
    @for(var i = 1; i<=4; i++)
    {
        

        if(Model.Count > j)
        {
            var color = getColorByType(Model[j].IdSubjectType);

            if(Model[j].WeekNumber == i)
            {
                <td style=@("background-color:"+color)>@(Model[j].SubjectName) (@getTypeNameByType(Model[j].IdSubjectType))     </td>
                <td style=@("background-color:"+color) rowspan="2" class="vertical-center">@Model[j].Classroom</td>
                j++;
            }
             else
            {
                <td></td>
                <td rowspan="2" class="vertical-center"></td>
            } 
        }
        else
        {
            <td></td>
            <td rowspan="2" class="vertical-center"></td>
        }
    }
    
</tr>
<tr>
    @{j = 0;}
    @for(var i = 1; i<=4; i++)
    {
        if(Model.Count > j)
        {
            var color = getColorByType(Model[j].IdSubjectType);

            if(Model[j].WeekNumber == i)
            {
                <td style=@("background-color:"+color)>@(Model[j].LectureName)</td>
                j++;
            }
             else
            {
                <td></td>
            }
        }
        else
        {
            <td></td>
        }
    }

</tr>